source "https://www.rubygems.org"

# PostgreSQL driver
gem 'pg'

# Sinatra driver
gem 'sinatra'
gem 'sinatra-contrib'

# Use Thin for our web server
gem 'thin'

gem 'activesupport'
gem 'activerecord'

gem 'rake'

gem 'shotgun'

# gem 'dynamic_form'

group :test do
  gem 'awesome_print'
  gem 'faker'
  gem 'rspec'
end
